# ----------------------- #
#      Site Configs       #
# ----------------------- #

url: https://thekaiway.com
baseurl: "" # the subpath of your site, e.g. /blog
title: The Kai Way
subtitle: Pragmaticly hacking
author: Kai Chen
description:
github_username: kaichen
twitter_username:
google_analytics: "UA-16480900-1"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Handling Reading
safe: false
include: [".htaccess"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "README.markdown",
    "*.ru",
    "*.rb",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
  ]
encoding: "UTF-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: "/:year/:month/:day/:slug:output_ext"
paths:
  rss: /atom.xml

# Filtering Content
paginate: 8

# Plugins
remotetheme: kitian616/jekyll-TeXt-theme
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives

# ---
# Theme
# ---
header_pages:
  - archive
  - about.md
show_excerpts: true
comments:
  provider: disqus
  disqus:
    shortname: "thekaiway"
analytics:
  provider: google
  google:
    tracking_id: "UA-16480900-1"
    anonymize_ip: true

# ---
# Plugins
# ---
jekyll-archives:
  layouts:
    year: archive
    category: archive
    tag: archive
  enabled:
    - category
    - year
    - tags

feed:
  path: /atom.xml
  posts_limit: 12